---
- name: Run cleanup
  import_playbook: playbooks/cleanup.yml

- name: Deploy Applications
  hosts: all
  become: yes
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

- import_playbook: playbooks/deploy_haproxy.yml
- import_playbook: playbooks/deploy_api.yml
- import_playbook: playbooks/deploy_front.yml