all:
  children:
    front:
      hosts:
        front-vm:
          ansible_host: 192.168.1.21
          ansible_user: root
          ansible_ssh_pass: password
    api:
      hosts:
        api-vm:
          ansible_host: 192.168.1.20
          ansible_user: root
          ansible_ssh_pass: password