all:
  children:
    haproxy:
      hosts:
        haproxy-vm:
          ansible_host: 192.168.1.14
          ansible_user: "{{ vault_ansible_user }}"
          ansible_ssh_pass: "{{ vault_ansible_ssh_pass  }}"
    front:
      hosts:
        front-vm1:
          ansible_host: 192.168.1.21
          ansible_user: "{{ vault_ansible_user }}"
          ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
        front-vm2:
          ansible_host: 192.168.1.15
          ansible_user: "{{ vault_ansible_user }}"
          ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
    api:
      hosts:
        api-vm1:
          ansible_host: 192.168.1.20
          ansible_user: "{{ vault_ansible_user }}"
          ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
        api-vm2:
          ansible_host: 192.168.1.16
          ansible_user: "{{ vault_ansible_user }}"
          ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"