all:
  children:
    haproxy:
      hosts:
        haproxy-vm:
          ansible_host: 192.168.1.14
          ansible_user: root
          ansible_ssh_pass: password
    front:
      hosts:
        front-vm1:
          ansible_host: 192.168.1.21
          ansible_user: root
          ansible_ssh_pass: password
        front-vm2:
          ansible_host: 192.168.1.15
          ansible_user: root
          ansible_ssh_pass: password
    api:
      hosts:
        api-vm1:
          ansible_host: 192.168.1.20
          ansible_user: root
          ansible_ssh_pass: password
        api-vm2:
          ansible_host: 192.168.1.16
          ansible_user: root
          ansible_ssh_pass: password