all:
  children:
    haproxy:
      hosts:
        haproxy-vm:
          ansible_host: 192.168.1.14
    front:
      hosts:
        front-vm1:
          ansible_host: 192.168.1.21
        front-vm2:
          ansible_host: 192.168.1.15
    api:
      hosts:
        api-vm1:
          ansible_host: 192.168.1.20
        api-vm2:
          ansible_host: 192.168.1.16
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'