all:
  children:
    haproxy:
      hosts:
        haproxy-vm:
          ansible_host: 192.168.1.24
    front:
      hosts:
        front-vm1:
          ansible_host: 192.168.1.21
        front-vm2:
          ansible_host: 192.168.1.25
    api:
      hosts:
        api-vm1:
          ansible_host: 192.168.1.27
        api-vm2:
          ansible_host: 192.168.1.26
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'