---
- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - gnupg
      - git
    state: present
    update_cache: yes

- name: Add NodeSource GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    filename: nodesource

- name: Install Node.js and npm
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Remove application directory
  file:
    path: "{{ app_root }}"
    state: absent
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Create application directory
  file:
    path: "{{ app_root }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Clone NodeJs repository for user
  git:
    repo: "{{ repository_url_user }}"
    dest: "{{ app_root }}"
    version: "{{ git_branch | default('main') }}"
    force: true
  become_user: "{{ app_user }}"

- name: Install npm dependencies
  npm:
    path: "{{ app_root }}"
    state: present
  become_user: "{{ app_user }}"

- name: Create environment files
  template:
    src: env.user.j2
    dest: "{{ app_root }}/.env"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0644'
  become_user: "{{ app_user }}"

#- name: Setup key and cert for ssl
#  import_tasks: ssl.yml

- name: Install pm2
  ansible.builtin.shell: npm i pm2 -g
  args:
    chdir: "{{ app_root }}"

- name: kill the process if listen on port 3000
  ansible.builtin.shell: kill -9 $(lsof -t -i:3000) 2>/dev/null && echo "Process on port 3000 killed" || echo "No process found on port 3000"
  args:
    chdir: "{{ app_root }}"

- name: Remove existing app for port conflict
  ansible.builtin.shell: pm2 delete all
  args:
    chdir: "{{ app_root }}"

- name: Start app using pm2
  ansible.builtin.shell: pm2 start /services/cron.js -f
  args:
    chdir: "{{ app_root }}"
