cleanup_paths:
  - /tmp/*
  - /var/tmp/*
  - /var/lib/mongodb
log_paths:
  - /var/log/*.log
  - /var/log/*.gz
services_to_stop:
  - apache2
  - mongod
packages_to_remove:
  - nodejs
  - npm
  - apache2
  - mongod
script_path: '/tmp/cleanup.sh'