---
- name: Deploy VueJS application
  hosts: front
  become: yes
  roles:
    - roles/apache
    - roles/vuejs
  tasks:
    - name: Build VueJS application
      command: npm run build
      args:
        chdir: "{{ app_root }}"
      become_user: "{{ app_user }}"

    - name: Restart apache
      service:
        name: apache
        state: restarted